baseURL = "https://callmenick.com/"
languageCode = "en-us"
title = "Call Me Nick"
theme = "callmenick"
[params]
  subtitle = "Bit Of This & That"
  description = "I'm a software engineer, and I focus on bringing joy and delight to users."
  author = "Nick Salloum"
